INSERT INTO number (value) VALUES ('1');
INSERT INTO number (value) VALUES ('2.0');
INSERT INTO number (value) VALUES ('3');
INSERT INTO number (value) VALUES ('4');
INSERT INTO number (value) VALUES ('10.2');
INSERT INTO number (value) VALUES ('20');
INSERT INTO number (value) VALUES ('20.999');
INSERT INTO number (value) VALUES ('0');
INSERT INTO number (value) VALUES ('100');
